# Site
name: 'OpenHW'
description: 'OpenHW is a website that accomodate various opensource projects'
#logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/OpenHW'
url: ""
disqus: 'demowebsite'
email: 'xup_shanghai@xilinx.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    XUP-2020:
      name:           XUP-2020        
      avatar:         /assets/images/avatar1.jpg
      bio:            "Collection of all projects in competitions of year 2020"
      email:          xup@xilinx.com

    XUP-2019:
      name:           XUP-2019
      avatar:         /assets/images/avatar1.jpg
      bio:            "Collection of all projects in competitions of year 2019"
      email:          xup@xilinx.com
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: XUP-2020
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]